steps:
  - name: python:3.12-slim
    id: 'tests'
    entrypoint: /bin/bash
    args:
      - -c
      - |
        pip install --user -r requirements.txt
        export PATH="$$PATH:/builder/home/.local/bin"
        export PYTHONPATH=$$PYTHONPATH:$$(pwd)

        python3 -m unittest -v ./tests/test_gcp.py
    waitFor: ['-']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'bigquery-schema'
    entrypoint: 'gsutil'
    args: ['cp', 'censo_schema.json', '${_INPUT_LOCATION}/censo_schema.json']
    waitFor: ['tests']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'
      - '.'
    waitFor: ['bigquery-schema']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'
    waitFor: ['build-image']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'build-template'
    entrypoint: 'gcloud'
    args:
      - 'dataflow'
      - 'flex-template'
      - 'build'
      - 'gs://${_TEMPLATE_BUCKET}/templates/censo-pipeline.json'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'
      - '--metadata-file'
      - 'metadata.json'
      - '--sdk-language'
      - 'PYTHON'
      - '--worker-machine-type'
      - '${_MACHINE_TYPE}'
    waitFor: ['push-image']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'dataflow'
      - 'flex-template'
      - 'run'
      - '${_JOB_NAME}'
      - '--template-file-gcs-location'
      - 'gs://${_TEMPLATE_BUCKET}/templates/censo-pipeline.json'
      - '--region'
      - '${_REGION}'
      - '--worker-region'
      - '${_WORKER_REGION}'
      - '--launcher-machine-type'
      - '${_MACHINE_TYPE}'
      - '--worker-machine-type'
      - '${_MACHINE_TYPE}'
      - '--parameters'
      - 'project=${_PROJECT},region=${_REGION},dataset=${_DATASET},table=${_TABLE},input_location=${_INPUT_LOCATION},staging_location=${_STAGING_LOCATION},output_location=${_OUTPUT_LOCATION},job_name=${_JOB_NAME},service_account_email=${_SA_EMAIL}'
    waitFor: ['build-template']

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT: etl-censo
  _REGION: us-central1
  _WORKER_REGION: us-central1
  _REPO_NAME: censo-artifact-repo
  _IMAGE_NAME: censo2024-pipeline
  _TEMPLATE_BUCKET: etl-censo-df
  _JOB_NAME: etl-censo-job-01
  _DATASET: ds_censo
  _TABLE: tbl_censo
  _INPUT_LOCATION: gs://etl-censo-df/input
  _STAGING_LOCATION: gs://etl-censo-df/temp/staging
  _OUTPUT_LOCATION: gs://etl-censo-df/out
  _SA_EMAIL: dataflow-app-sa@etl-censo.iam.gserviceaccount.com
  _MACHINE_TYPE: e2-standard-2

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'

timeout: '1800s'
