steps:
  # Paso 1: Testing
  - name: python:3.12-slim
    id: 'tests'
    entrypoint: /bin/bash
    args:
      - -c
      - |
        pip install --user -r requirements.txt
        export PATH="$$PATH:/builder/home/.local/bin"
        export PYTHONPATH=$$PYTHONPATH:$$(pwd)

        python3 -m unittest -v ./tests/test_gcp.py
    waitFor: ['-']

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT: etl-censo
  _REGION: us-central1
  _WORKER_REGION: us-central1
  _REPO_NAME: censo-artifact-repo
  _IMAGE_NAME: censo2024-pipeline
  _TEMPLATE_BUCKET: etl-censo-df
  _JOB_NAME: etl-censo-job-01
  _DATASET: ds_censo
  _TABLE: tbl_censo
  _INPUT_LOCATION: gs://etl-censo-df/input
  _STAGING_LOCATION: gs://etl-censo-df/temp/staging
  _OUTPUT_LOCATION: gs://etl-censo-df/out
  _SA_EMAIL: dataflow-app-sa@etl-censo.iam.gserviceaccount.com
  _MACHINE_TYPE: e2-standard-2

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'

timeout: '1800s'
