from collections import namedtuple

CodigoTerritorial = namedtuple(
    "CodigoTerritorial",
    ["Codigo", "Division", "Territorio"]
)

CODIGOS_TERRITORIALES = [
    CodigoTerritorial("1", "Región", "Tarapacá"),
    CodigoTerritorial("2", "Región", "Antofagasta"),
    CodigoTerritorial("3", "Región", "Atacama"),
    CodigoTerritorial("4", "Región", "Coquimbo"),
    CodigoTerritorial("5", "Región", "Valparaíso"),
    CodigoTerritorial(
        "6", "Región", "Libertador General Bernardo O'Higgins"),
    CodigoTerritorial("7", "Región", "Maule"),
    CodigoTerritorial("8", "Región", "Biobío"),
    CodigoTerritorial("9", "Región", "La Araucanía"),
    CodigoTerritorial("10", "Región", "Los Lagos"),
    CodigoTerritorial(
        "11", "Región", "Aysén del General Carlos Ibáñez del Campo"),
    CodigoTerritorial("12", "Región", "Magallanes y de la Antártica Chilena"),
    CodigoTerritorial("13", "Región", "Metropolitana de Santiago"),
    CodigoTerritorial("14", "Región", "Los Ríos"),
    CodigoTerritorial("15", "Región", "Arica y Parinacota"),
    CodigoTerritorial("16", "Región", "Ñuble"),
    CodigoTerritorial("11", "Provincia", "Iquique"),
    CodigoTerritorial("14", "Provincia", "Del Tamarugal"),
    CodigoTerritorial("21", "Provincia", "Antofagasta"),
    CodigoTerritorial("22", "Provincia", "El Loa"),
    CodigoTerritorial("23", "Provincia", "Tocopilla"),
    CodigoTerritorial("31", "Provincia", "Copiapó"),
    CodigoTerritorial("32", "Provincia", "Chañaral"),
    CodigoTerritorial("33", "Provincia", "Huasco"),
    CodigoTerritorial("41", "Provincia", "Elqui"),
    CodigoTerritorial("42", "Provincia", "Choapa"),
    CodigoTerritorial("43", "Provincia", "Limarí"),
    CodigoTerritorial("51", "Provincia", "Valparaíso"),
    CodigoTerritorial("52", "Provincia", "Isla de Pascua"),
    CodigoTerritorial("53", "Provincia", "Los Andes"),
    CodigoTerritorial("54", "Provincia", "Petorca"),
    CodigoTerritorial("55", "Provincia", "Quillota"),
    CodigoTerritorial("56", "Provincia", "San Antonio"),
    CodigoTerritorial("57", "Provincia", "San Felipe de Aconcagua"),
    CodigoTerritorial("58", "Provincia", "Marga Marga"),
    CodigoTerritorial("61", "Provincia", "Cachapoal"),
    CodigoTerritorial("62", "Provincia", "Cardenal Caro"),
    CodigoTerritorial("63", "Provincia", "Colchagua"),
    CodigoTerritorial("71", "Provincia", "Talca"),
    CodigoTerritorial("72", "Provincia", "Cauquenes"),
    CodigoTerritorial("73", "Provincia", "Curicó"),
    CodigoTerritorial("74", "Provincia", "Linares"),
    CodigoTerritorial("81", "Provincia", "Concepción"),
    CodigoTerritorial("82", "Provincia", "Arauco"),
    CodigoTerritorial("83", "Provincia", "Biobío"),
    CodigoTerritorial("91", "Provincia", "Cautín"),
    CodigoTerritorial("92", "Provincia", "Malleco"),
    CodigoTerritorial("101", "Provincia", "Llanquihue"),
    CodigoTerritorial("102", "Provincia", "Chiloé"),
    CodigoTerritorial("103", "Provincia", "Osorno"),
    CodigoTerritorial("104", "Provincia", "Palena"),
    CodigoTerritorial("111", "Provincia", "Coyhaique"),
    CodigoTerritorial("112", "Provincia", "Aysén"),
    CodigoTerritorial("113", "Provincia", "Capitán Prat"),
    CodigoTerritorial("114", "Provincia", "General Carrera"),
    CodigoTerritorial("121", "Provincia", "Magallanes"),
    CodigoTerritorial("122", "Provincia", "Antártica Chilena"),
    CodigoTerritorial("123", "Provincia", "Tierra del Fuego"),
    CodigoTerritorial("124", "Provincia", "Última Esperanza"),
    CodigoTerritorial("131", "Provincia", "Santiago"),
    CodigoTerritorial("132", "Provincia", "Cordillera"),
    CodigoTerritorial("133", "Provincia", "Chacabuco"),
    CodigoTerritorial("134", "Provincia", "Maipo"),
    CodigoTerritorial("135", "Provincia", "Melipilla"),
    CodigoTerritorial("136", "Provincia", "Talagante"),
    CodigoTerritorial("141", "Provincia", "Valdivia"),
    CodigoTerritorial("142", "Provincia", "Ranco"),
    CodigoTerritorial("151", "Provincia", "Arica"),
    CodigoTerritorial("152", "Provincia", "Parinacota"),
    CodigoTerritorial("161", "Provincia", "Diguillín"),
    CodigoTerritorial("162", "Provincia", "Itata"),
    CodigoTerritorial("163", "Provincia", "Punilla"),
    CodigoTerritorial("1101", "Comuna", "Iquique"),
    CodigoTerritorial("1107", "Comuna", "Alto Hospicio"),
    CodigoTerritorial("1401", "Comuna", "Pozo Almonte"),
    CodigoTerritorial("1402", "Comuna", "Camiña"),
    CodigoTerritorial("1403", "Comuna", "Colchane"),
    CodigoTerritorial("1404", "Comuna", "Huara"),
    CodigoTerritorial("1405", "Comuna", "Pica"),
    CodigoTerritorial("2101", "Comuna", "Antofagasta"),
    CodigoTerritorial("2102", "Comuna", "Mejillones"),
    CodigoTerritorial("2103", "Comuna", "Sierra Gorda"),
    CodigoTerritorial("2104", "Comuna", "Taltal"),
    CodigoTerritorial("2201", "Comuna", "Calama"),
    CodigoTerritorial("2202", "Comuna", "Ollagüe"),
    CodigoTerritorial("2203", "Comuna", "San Pedro de Atacama"),
    CodigoTerritorial("2301", "Comuna", "Tocopilla"),
    CodigoTerritorial("2302", "Comuna", "María Elena"),
    CodigoTerritorial("3101", "Comuna", "Copiapó"),
    CodigoTerritorial("3102", "Comuna", "Caldera"),
    CodigoTerritorial("3103", "Comuna", "Tierra Amarilla"),
    CodigoTerritorial("3201", "Comuna", "Chañaral"),
    CodigoTerritorial("3202", "Comuna", "Diego de Almagro"),
    CodigoTerritorial("3301", "Comuna", "Vallenar"),
    CodigoTerritorial("3302", "Comuna", "Alto del Carmen"),
    CodigoTerritorial("3303", "Comuna", "Freirina"),
    CodigoTerritorial("3304", "Comuna", "Huasco"),
    CodigoTerritorial("4101", "Comuna", "La Serena"),
    CodigoTerritorial("4102", "Comuna", "Coquimbo"),
    CodigoTerritorial("4103", "Comuna", "Andacollo"),
    CodigoTerritorial("4104", "Comuna", "La Higuera"),
    CodigoTerritorial("4105", "Comuna", "Paihuano"),
    CodigoTerritorial("4106", "Comuna", "Vicuña"),
    CodigoTerritorial("4201", "Comuna", "Illapel"),
    CodigoTerritorial("4202", "Comuna", "Canela"),
    CodigoTerritorial("4203", "Comuna", "Los Vilos"),
    CodigoTerritorial("4204", "Comuna", "Salamanca"),
    CodigoTerritorial("4301", "Comuna", "Ovalle"),
    CodigoTerritorial("4302", "Comuna", "Combarbalá"),
    CodigoTerritorial("4303", "Comuna", "Monte Patria"),
    CodigoTerritorial("4304", "Comuna", "Punitaqui"),
    CodigoTerritorial("4305", "Comuna", "Río Hurtado"),
    CodigoTerritorial("5101", "Comuna", "Valparaíso"),
    CodigoTerritorial("5102", "Comuna", "Casablanca"),
    CodigoTerritorial("5103", "Comuna", "Concón"),
    CodigoTerritorial("5104", "Comuna", "Juan Fernández"),
    CodigoTerritorial("5105", "Comuna", "Puchuncaví"),
    CodigoTerritorial("5107", "Comuna", "Quintero"),
    CodigoTerritorial("5109", "Comuna", "Viña del Mar"),
    CodigoTerritorial("5201", "Comuna", "Isla de Pascua"),
    CodigoTerritorial("5301", "Comuna", "Los Andes"),
    CodigoTerritorial("5302", "Comuna", "Calle Larga"),
    CodigoTerritorial("5303", "Comuna", "Rinconada"),
    CodigoTerritorial("5304", "Comuna", "San Esteban"),
    CodigoTerritorial("5401", "Comuna", "La Ligua"),
    CodigoTerritorial("5402", "Comuna", "Cabildo"),
    CodigoTerritorial("5403", "Comuna", "Papudo"),
    CodigoTerritorial("5404", "Comuna", "Petorca"),
    CodigoTerritorial("5405", "Comuna", "Zapallar"),
    CodigoTerritorial("5501", "Comuna", "Quillota"),
    CodigoTerritorial("5502", "Comuna", "Calera"),
    CodigoTerritorial("5503", "Comuna", "Hijuelas"),
    CodigoTerritorial("5504", "Comuna", "La Cruz"),
    CodigoTerritorial("5506", "Comuna", "Nogales"),
    CodigoTerritorial("5601", "Comuna", "San Antonio"),
    CodigoTerritorial("5602", "Comuna", "Algarrobo"),
    CodigoTerritorial("5603", "Comuna", "Cartagena"),
    CodigoTerritorial("5604", "Comuna", "El Quisco"),
    CodigoTerritorial("5605", "Comuna", "El Tabo"),
    CodigoTerritorial("5606", "Comuna", "Santo Domingo"),
    CodigoTerritorial("5701", "Comuna", "San Felipe"),
    CodigoTerritorial("5702", "Comuna", "Catemu"),
    CodigoTerritorial("5703", "Comuna", "Llaillay"),
    CodigoTerritorial("5704", "Comuna", "Panquehue"),
    CodigoTerritorial("5705", "Comuna", "Putaendo"),
    CodigoTerritorial("5706", "Comuna", "Santa María"),
    CodigoTerritorial("5801", "Comuna", "Quilpué"),
    CodigoTerritorial("5802", "Comuna", "Limache"),
    CodigoTerritorial("5803", "Comuna", "Olmué"),
    CodigoTerritorial("5804", "Comuna", "Villa Alemana"),
    CodigoTerritorial("6101", "Comuna", "Rancagua"),
    CodigoTerritorial("6102", "Comuna", "Codegua"),
    CodigoTerritorial("6103", "Comuna", "Coinco"),
    CodigoTerritorial("6104", "Comuna", "Coltauco"),
    CodigoTerritorial("6105", "Comuna", "Doñihue"),
    CodigoTerritorial("6106", "Comuna", "Graneros"),
    CodigoTerritorial("6107", "Comuna", "Las Cabras"),
    CodigoTerritorial("6108", "Comuna", "Machalí"),
    CodigoTerritorial("6109", "Comuna", "Malloa"),
    CodigoTerritorial("6110", "Comuna", "Mostazal"),
    CodigoTerritorial("6111", "Comuna", "Olivar"),
    CodigoTerritorial("6112", "Comuna", "Peumo"),
    CodigoTerritorial("6113", "Comuna", "Pichidegua"),
    CodigoTerritorial("6114", "Comuna", "Quinta de Tilcoco"),
    CodigoTerritorial("6115", "Comuna", "Rengo"),
    CodigoTerritorial("6116", "Comuna", "Requínoa"),
    CodigoTerritorial("6117", "Comuna", "San Vicente"),
    CodigoTerritorial("6201", "Comuna", "Pichilemu"),
    CodigoTerritorial("6202", "Comuna", "La Estrella"),
    CodigoTerritorial("6203", "Comuna", "Litueche"),
    CodigoTerritorial("6204", "Comuna", "Marchihue"),
    CodigoTerritorial("6205", "Comuna", "Navidad"),
    CodigoTerritorial("6206", "Comuna", "Paredones"),
    CodigoTerritorial("6301", "Comuna", "San Fernando"),
    CodigoTerritorial("6302", "Comuna", "Chépica"),
    CodigoTerritorial("6303", "Comuna", "Chimbarongo"),
    CodigoTerritorial("6304", "Comuna", "Lolol"),
    CodigoTerritorial("6305", "Comuna", "Nancagua"),
    CodigoTerritorial("6306", "Comuna", "Palmilla"),
    CodigoTerritorial("6307", "Comuna", "Peralillo"),
    CodigoTerritorial("6308", "Comuna", "Placilla"),
    CodigoTerritorial("6309", "Comuna", "Pumanque"),
    CodigoTerritorial("6310", "Comuna", "Santa Cruz"),
    CodigoTerritorial("7101", "Comuna", "Talca"),
    CodigoTerritorial("7102", "Comuna", "Constitución"),
    CodigoTerritorial("7103", "Comuna", "Curepto"),
    CodigoTerritorial("7104", "Comuna", "Empedrado"),
    CodigoTerritorial("7105", "Comuna", "Maule"),
    CodigoTerritorial("7106", "Comuna", "Pelarco"),
    CodigoTerritorial("7107", "Comuna", "Pencahue"),
    CodigoTerritorial("7108", "Comuna", "Río Claro"),
    CodigoTerritorial("7109", "Comuna", "San Clemente"),
    CodigoTerritorial("7110", "Comuna", "San Rafael"),
    CodigoTerritorial("7201", "Comuna", "Cauquenes"),
    CodigoTerritorial("7202", "Comuna", "Chanco"),
    CodigoTerritorial("7203", "Comuna", "Pelluhue"),
    CodigoTerritorial("7301", "Comuna", "Curicó"),
    CodigoTerritorial("7302", "Comuna", "Hualañé"),
    CodigoTerritorial("7303", "Comuna", "Licantén"),
    CodigoTerritorial("7304", "Comuna", "Molina"),
    CodigoTerritorial("7305", "Comuna", "Rauco"),
    CodigoTerritorial("7306", "Comuna", "Romeral"),
    CodigoTerritorial("7307", "Comuna", "Sagrada Familia"),
    CodigoTerritorial("7308", "Comuna", "Teno"),
    CodigoTerritorial("7309", "Comuna", "Vichuquén"),
    CodigoTerritorial("7401", "Comuna", "Linares"),
    CodigoTerritorial("7402", "Comuna", "Colbún"),
    CodigoTerritorial("7403", "Comuna", "Longaví"),
    CodigoTerritorial("7404", "Comuna", "Parral"),
    CodigoTerritorial("7405", "Comuna", "Retiro"),
    CodigoTerritorial("7406", "Comuna", "San Javier"),
    CodigoTerritorial("7407", "Comuna", "Villa Alegre"),
    CodigoTerritorial("7408", "Comuna", "Yerbas Buenas"),
    CodigoTerritorial("8101", "Comuna", "Concepción"),
    CodigoTerritorial("8102", "Comuna", "Coronel"),
    CodigoTerritorial("8103", "Comuna", "Chiguayante"),
    CodigoTerritorial("8104", "Comuna", "Florida"),
    CodigoTerritorial("8105", "Comuna", "Hualqui"),
    CodigoTerritorial("8106", "Comuna", "Lota"),
    CodigoTerritorial("8107", "Comuna", "Penco"),
    CodigoTerritorial("8108", "Comuna", "San Pedro de La paz"),
    CodigoTerritorial("8109", "Comuna", "Santa Juana"),
    CodigoTerritorial("8110", "Comuna", "Talcahuano"),
    CodigoTerritorial("8111", "Comuna", "Tomé"),
    CodigoTerritorial("8112", "Comuna", "Hualpén"),
    CodigoTerritorial("8201", "Comuna", "Lebu"),
    CodigoTerritorial("8202", "Comuna", "Arauco"),
    CodigoTerritorial("8203", "Comuna", "Cañete"),
    CodigoTerritorial("8204", "Comuna", "Contulmo"),
    CodigoTerritorial("8205", "Comuna", "Curanilahue"),
    CodigoTerritorial("8206", "Comuna", "Los Álamos"),
    CodigoTerritorial("8207", "Comuna", "Tirúa"),
    CodigoTerritorial("8301", "Comuna", "Los Ángeles"),
    CodigoTerritorial("8302", "Comuna", "Antuco"),
    CodigoTerritorial("8303", "Comuna", "Cabrero"),
    CodigoTerritorial("8304", "Comuna", "Laja"),
    CodigoTerritorial("8305", "Comuna", "Mulchén"),
    CodigoTerritorial("8306", "Comuna", "Nacimiento"),
    CodigoTerritorial("8307", "Comuna", "Negrete"),
    CodigoTerritorial("8308", "Comuna", "Quilaco"),
    CodigoTerritorial("8309", "Comuna", "Quilleco"),
    CodigoTerritorial("8310", "Comuna", "San Rosendo"),
    CodigoTerritorial("8311", "Comuna", "Santa Bárbara"),
    CodigoTerritorial("8312", "Comuna", "Tucapel"),
    CodigoTerritorial("8313", "Comuna", "Yumbel"),
    CodigoTerritorial("8314", "Comuna", "Alto Biobío"),
    CodigoTerritorial("9101", "Comuna", "Temuco"),
    CodigoTerritorial("9102", "Comuna", "Carahue"),
    CodigoTerritorial("9103", "Comuna", "Cunco"),
    CodigoTerritorial("9104", "Comuna", "Curarrehue"),
    CodigoTerritorial("9105", "Comuna", "Freire"),
    CodigoTerritorial("9106", "Comuna", "Galvarino"),
    CodigoTerritorial("9107", "Comuna", "Gorbea"),
    CodigoTerritorial("9108", "Comuna", "Lautaro"),
    CodigoTerritorial("9109", "Comuna", "Loncoche"),
    CodigoTerritorial("9110", "Comuna", "Melipeuco"),
    CodigoTerritorial("9111", "Comuna", "Nueva Imperial"),
    CodigoTerritorial("9112", "Comuna", "Padre Las Casas"),
    CodigoTerritorial("9113", "Comuna", "Perquenco"),
    CodigoTerritorial("9114", "Comuna", "Pitrufquén"),
    CodigoTerritorial("9115", "Comuna", "Pucón"),
    CodigoTerritorial("9116", "Comuna", "Saavedra"),
    CodigoTerritorial("9117", "Comuna", "Teodoro Schmidt"),
    CodigoTerritorial("9118", "Comuna", "Toltén"),
    CodigoTerritorial("9119", "Comuna", "Vilcún"),
    CodigoTerritorial("9120", "Comuna", "Villarrica"),
    CodigoTerritorial("9121", "Comuna", "Cholchol"),
    CodigoTerritorial("9201", "Comuna", "Angol"),
    CodigoTerritorial("9202", "Comuna", "Collipulli"),
    CodigoTerritorial("9203", "Comuna", "Curacautín"),
    CodigoTerritorial("9204", "Comuna", "Ercilla"),
    CodigoTerritorial("9205", "Comuna", "Lonquimay"),
    CodigoTerritorial("9206", "Comuna", "Los Sauces"),
    CodigoTerritorial("9207", "Comuna", "Lumaco"),
    CodigoTerritorial("9208", "Comuna", "Purén"),
    CodigoTerritorial("9209", "Comuna", "Renaico"),
    CodigoTerritorial("9210", "Comuna", "Traiguén"),
    CodigoTerritorial("9211", "Comuna", "Victoria"),
    CodigoTerritorial("10101", "Comuna", "Puerto Montt"),
    CodigoTerritorial("10102", "Comuna", "Calbuco"),
    CodigoTerritorial("10103", "Comuna", "Cochamó"),
    CodigoTerritorial("10104", "Comuna", "Fresia"),
    CodigoTerritorial("10105", "Comuna", "Frutillar"),
    CodigoTerritorial("10106", "Comuna", "Los Muermos"),
    CodigoTerritorial("10107", "Comuna", "Llanquihue"),
    CodigoTerritorial("10108", "Comuna", "Maullín"),
    CodigoTerritorial("10109", "Comuna", "Puerto Varas"),
    CodigoTerritorial("10201", "Comuna", "Castro"),
    CodigoTerritorial("10202", "Comuna", "Ancud"),
    CodigoTerritorial("10203", "Comuna", "Chonchi"),
    CodigoTerritorial("10204", "Comuna", "Curaco de Vélez"),
    CodigoTerritorial("10205", "Comuna", "Dalcahue"),
    CodigoTerritorial("10206", "Comuna", "Puqueldón"),
    CodigoTerritorial("10207", "Comuna", "Queilén"),
    CodigoTerritorial("10208", "Comuna", "Quellón"),
    CodigoTerritorial("10209", "Comuna", "Quemchi"),
    CodigoTerritorial("10210", "Comuna", "Quinchao"),
    CodigoTerritorial("10301", "Comuna", "Osorno"),
    CodigoTerritorial("10302", "Comuna", "Puerto Octay"),
    CodigoTerritorial("10303", "Comuna", "Purranque"),
    CodigoTerritorial("10304", "Comuna", "Puyehue"),
    CodigoTerritorial("10305", "Comuna", "Río Negro"),
    CodigoTerritorial("10306", "Comuna", "San Juan de la Costa"),
    CodigoTerritorial("10307", "Comuna", "San Pablo"),
    CodigoTerritorial("10401", "Comuna", "Chaitén"),
    CodigoTerritorial("10402", "Comuna", "Futaleufú"),
    CodigoTerritorial("10403", "Comuna", "Hualaihué"),
    CodigoTerritorial("10404", "Comuna", "Palena"),
    CodigoTerritorial("11101", "Comuna", "Coyhaique"),
    CodigoTerritorial("11102", "Comuna", "Lago Verde"),
    CodigoTerritorial("11201", "Comuna", "Aysén"),
    CodigoTerritorial("11202", "Comuna", "Cisnes"),
    CodigoTerritorial("11203", "Comuna", "Guaitecas"),
    CodigoTerritorial("11301", "Comuna", "Cochrane"),
    CodigoTerritorial("11302", "Comuna", "O'Higgins"),
    CodigoTerritorial("11303", "Comuna", "Tortel"),
    CodigoTerritorial("11401", "Comuna", "Chile Chico"),
    CodigoTerritorial("11402", "Comuna", "Río Ibáñez"),
    CodigoTerritorial("12101", "Comuna", "Punta Arenas"),
    CodigoTerritorial("12102", "Comuna", "Laguna Blanca"),
    CodigoTerritorial("12103", "Comuna", "Río Verde"),
    CodigoTerritorial("12104", "Comuna", "San Gregorio"),
    CodigoTerritorial("12201", "Comuna", "Cabo de Hornos"),
    CodigoTerritorial("12202", "Comuna", "Antártica"),
    CodigoTerritorial("12301", "Comuna", "Porvenir"),
    CodigoTerritorial("12302", "Comuna", "Primavera"),
    CodigoTerritorial("12303", "Comuna", "Timaukel"),
    CodigoTerritorial("12401", "Comuna", "Natales"),
    CodigoTerritorial("12402", "Comuna", "Torres del Paine"),
    CodigoTerritorial("13101", "Comuna", "Santiago"),
    CodigoTerritorial("13102", "Comuna", "Cerrillos"),
    CodigoTerritorial("13103", "Comuna", "Cerro Navia"),
    CodigoTerritorial("13104", "Comuna", "Conchalí"),
    CodigoTerritorial("13105", "Comuna", "El Bosque"),
    CodigoTerritorial("13106", "Comuna", "Estación Central"),
    CodigoTerritorial("13107", "Comuna", "Huechuraba"),
    CodigoTerritorial("13108", "Comuna", "Independencia"),
    CodigoTerritorial("13109", "Comuna", "La Cisterna"),
    CodigoTerritorial("13110", "Comuna", "La Florida"),
    CodigoTerritorial("13111", "Comuna", "La Granja"),
    CodigoTerritorial("13112", "Comuna", "La Pintana"),
    CodigoTerritorial("13113", "Comuna", "La Reina"),
    CodigoTerritorial("13114", "Comuna", "Las Condes"),
    CodigoTerritorial("13115", "Comuna", "Lo Barnechea"),
    CodigoTerritorial("13116", "Comuna", "Lo Espejo"),
    CodigoTerritorial("13117", "Comuna", "Lo Prado"),
    CodigoTerritorial("13118", "Comuna", "Macul"),
    CodigoTerritorial("13119", "Comuna", "Maipú"),
    CodigoTerritorial("13120", "Comuna", "Ñuñoa"),
    CodigoTerritorial("13121", "Comuna", "Pedro Aguirre Cerda"),
    CodigoTerritorial("13122", "Comuna", "Peñalolén"),
    CodigoTerritorial("13123", "Comuna", "Providencia"),
    CodigoTerritorial("13124", "Comuna", "Pudahuel"),
    CodigoTerritorial("13125", "Comuna", "Quilicura"),
    CodigoTerritorial("13126", "Comuna", "Quinta Normal"),
    CodigoTerritorial("13127", "Comuna", "Recoleta"),
    CodigoTerritorial("13128", "Comuna", "Renca"),
    CodigoTerritorial("13129", "Comuna", "San Joaquín"),
    CodigoTerritorial("13130", "Comuna", "San Miguel"),
    CodigoTerritorial("13131", "Comuna", "San Ramón"),
    CodigoTerritorial("13132", "Comuna", "Vitacura"),
    CodigoTerritorial("13201", "Comuna", "Puente Alto"),
    CodigoTerritorial("13202", "Comuna", "Pirque"),
    CodigoTerritorial("13203", "Comuna", "San José de Maipo"),
    CodigoTerritorial("13301", "Comuna", "Colina"),
    CodigoTerritorial("13302", "Comuna", "Lampa"),
    CodigoTerritorial("13303", "Comuna", "Tiltil"),
    CodigoTerritorial("13401", "Comuna", "San Bernardo"),
    CodigoTerritorial("13402", "Comuna", "Buin"),
    CodigoTerritorial("13403", "Comuna", "Calera de Tango"),
    CodigoTerritorial("13404", "Comuna", "Paine"),
    CodigoTerritorial("13501", "Comuna", "Melipilla"),
    CodigoTerritorial("13502", "Comuna", "Alhué"),
    CodigoTerritorial("13503", "Comuna", "Curacaví"),
    CodigoTerritorial("13504", "Comuna", "María Pinto"),
    CodigoTerritorial("13505", "Comuna", "San Pedro"),
    CodigoTerritorial("13601", "Comuna", "Talagante"),
    CodigoTerritorial("13602", "Comuna", "El Monte"),
    CodigoTerritorial("13603", "Comuna", "Isla de Maipo"),
    CodigoTerritorial("13604", "Comuna", "Padre Hurtado"),
    CodigoTerritorial("13605", "Comuna", "Peñaflor"),
    CodigoTerritorial("14101", "Comuna", "Valdivia"),
    CodigoTerritorial("14102", "Comuna", "Corral"),
    CodigoTerritorial("14103", "Comuna", "Lanco"),
    CodigoTerritorial("14104", "Comuna", "Los Lagos"),
    CodigoTerritorial("14105", "Comuna", "Máfil"),
    CodigoTerritorial("14106", "Comuna", "Mariquina"),
    CodigoTerritorial("14107", "Comuna", "Paillaco"),
    CodigoTerritorial("14108", "Comuna", "Panguipulli"),
    CodigoTerritorial("14201", "Comuna", "La Unión"),
    CodigoTerritorial("14202", "Comuna", "Futrono"),
    CodigoTerritorial("14203", "Comuna", "Lago Ranco"),
    CodigoTerritorial("14204", "Comuna", "Río Bueno"),
    CodigoTerritorial("15101", "Comuna", "Arica"),
    CodigoTerritorial("15102", "Comuna", "Camarones"),
    CodigoTerritorial("15201", "Comuna", "Putre"),
    CodigoTerritorial("15202", "Comuna", "General Lagos"),
    CodigoTerritorial("16101", "Comuna", "Chillán"),
    CodigoTerritorial("16102", "Comuna", "Bulnes"),
    CodigoTerritorial("16103", "Comuna", "Chillán Viejo"),
    CodigoTerritorial("16104", "Comuna", "El Carmen"),
    CodigoTerritorial("16105", "Comuna", "Pemuco"),
    CodigoTerritorial("16106", "Comuna", "Pinto"),
    CodigoTerritorial("16107", "Comuna", "Quillón"),
    CodigoTerritorial("16108", "Comuna", "San Ignacio"),
    CodigoTerritorial("16109", "Comuna", "Yungay"),
    CodigoTerritorial("16201", "Comuna", "Quirihue"),
    CodigoTerritorial("16202", "Comuna", "Cobquecura"),
    CodigoTerritorial("16203", "Comuna", "Coelemu"),
    CodigoTerritorial("16204", "Comuna", "Ninhue"),
    CodigoTerritorial("16205", "Comuna", "Portezuelo"),
    CodigoTerritorial("16206", "Comuna", "Ránquil"),
    CodigoTerritorial("16207", "Comuna", "Trehuaco"),
    CodigoTerritorial("16301", "Comuna", "San Carlos"),
    CodigoTerritorial("16302", "Comuna", "Coihueco"),
    CodigoTerritorial("16303", "Comuna", "Ñiquén"),
    CodigoTerritorial("16304", "Comuna", "San Fabián"),
    CodigoTerritorial("16305", "Comuna", "San Nicolás")
]
