from collections import namedtuple

CodigoOtro = namedtuple(
    "CodigoOtro",
    ["Campo", "Codigo", "Descripcion"]
)

CODIGOS_OTROS = [
    CodigoOtro("Campo", "Codigo", "Descripcion"),
    CodigoOtro("area", "1", "Urbano"),
    CodigoOtro("area", "2", "Rural"),
    CodigoOtro("tipo_operativo", "1", "Persona en situación de calle"),
    CodigoOtro("tipo_operativo", "2", "Vivienda particular"),
    CodigoOtro("tipo_operativo", "3", "Vivienda colectiva"),
    CodigoOtro("p2_tipo_vivienda", "1", "Casa"),
    CodigoOtro("p2_tipo_vivienda", "3", "Departamento"),
    CodigoOtro("p2_tipo_vivienda", "5",
               "Vivienda tradicional indígena (ruka u otras)"),
    CodigoOtro("p2_tipo_vivienda", "6",
               "Pieza en casa antigua o en conventillo"),
    CodigoOtro("p2_tipo_vivienda", "7",
               "Mediagua, mejora, vivienda de emergencia, rancho o choza"),
    CodigoOtro("p2_tipo_vivienda", "8",
               "Móvil (carpa, casa rodante o similar)"),
    CodigoOtro("p2_tipo_vivienda", "9", "Otro tipo de vivienda particular"),
    CodigoOtro("p2_tipo_vivienda", "NA", "No aplica"),
    CodigoOtro("p3a_estado_ocupacion", "1", "Ocupada"),
    CodigoOtro("p3a_estado_ocupacion", "2", "Desocupada"),
    CodigoOtro("p3a_estado_ocupacion", "NA", "No aplica"),
    CodigoOtro("p3b_estado_ocupacion", "1", "Moradores presentes"),
    CodigoOtro("p3b_estado_ocupacion", "2", "Moradores ausentes"),
    CodigoOtro("p3b_estado_ocupacion", "6", "Otras razones de no entrevista"),
    CodigoOtro("p3b_estado_ocupacion", "7", "En venta o arriendo"),
    CodigoOtro("p3b_estado_ocupacion", "8",
               "Vivienda de temporada (veraneo o de uso temporal)"),
    CodigoOtro("p3b_estado_ocupacion", "9", "Abandonada"),
    CodigoOtro("p3b_estado_ocupacion", "10", "Otra razón de desocupación"),
    CodigoOtro("p3b_estado_ocupacion", "NA", "No aplica"),
    CodigoOtro("p6_fuente_agua", "1", "Red pública"),
    CodigoOtro("p6_fuente_agua", "2", "Pozo o noria"),
    CodigoOtro("p6_fuente_agua", "3", "Camión aljibe"),
    CodigoOtro("p6_fuente_agua", "4",
               "Río, vertiente, estero, canal, lago, agua lluvia, etc."),
    CodigoOtro("p6_fuente_agua", "-99", "No respuesta"),
    CodigoOtro("p6_fuente_agua", "NA", "No aplica"),
    CodigoOtro("p8_serv_hig", "1",
               "Dentro de la vivienda, conectado a una red de alcantarillado"),
    CodigoOtro("p8_serv_hig", "2",
               "Fuera de la vivienda, conectado a una red de alcantarillado"),
    CodigoOtro("p8_serv_hig", "3", "Conectado a una fosa séptica"),
    CodigoOtro("p8_serv_hig", "4",
               "Conectado a pozo negro (letrina sanitaria o cajón)"),
    CodigoOtro("p8_serv_hig", "5", "En un cajón sobre acequia o canal"),
    CodigoOtro("p8_serv_hig", "6", "En un cajón conectado a otro sistema"),
    CodigoOtro("p8_serv_hig", "7", "Baño químico"),
    CodigoOtro("p8_serv_hig", "8", "Conectado a baño seco"),
    CodigoOtro("p8_serv_hig", "9", "No tiene servicio higiénico"),
    CodigoOtro("p8_serv_hig", "-99", "No respuesta"),
    CodigoOtro("p8_serv_hig", "NA", "No aplica"),
    CodigoOtro("p10_basura", "1", "La recogen los servicios de aseo"),
    CodigoOtro("p10_basura", "2", "La entierra y/o quema"),
    CodigoOtro("p10_basura", "3",
               "La deja en terreno eriazo, quebrada o zanja"),
    CodigoOtro("p10_basura", "4", "La tira al río, laguna o mar"),
    CodigoOtro("p10_basura", "5", "Otro"),
    CodigoOtro("p10_basura", "-99", "No respuesta"),
    CodigoOtro("p10_basura", "NA", "No aplica"),
    CodigoOtro("indice_hacinamiento", "1", "Vivienda sin hacinamiento"),
    CodigoOtro("indice_hacinamiento", "2", "Vivienda con hacinamiento medio"),
    CodigoOtro("indice_hacinamiento", "3",
               "Vivienda con hacinamiento crítico"),
    CodigoOtro("indice_hacinamiento", "-99", "No respuesta"),
    CodigoOtro("indice_hacinamiento", "NA", "No aplica"),
    CodigoOtro("p12_tenencia_viv", "1", "Propia pagada"),
    CodigoOtro("p12_tenencia_viv", "2", "Propia pagándose"),
    CodigoOtro("p12_tenencia_viv", "3", "Arrendada con contrato"),
    CodigoOtro("p12_tenencia_viv", "4", "Arrendada sin contrato"),
    CodigoOtro("p12_tenencia_viv", "5", "Cedida por trabajo o servicio"),
    CodigoOtro("p12_tenencia_viv", "6", "Cedida por familiar u otro"),
    CodigoOtro("p12_tenencia_viv", "7", "Usufructo: solo uso y goce"),
    CodigoOtro("p12_tenencia_viv", "8", "Ocupada de hecho"),
    CodigoOtro("p12_tenencia_viv", "9", "Propiedad en sucesión o litigio"),
    CodigoOtro("p12_tenencia_viv", "-99", "No respuesta"),
    CodigoOtro("p12_tenencia_viv", "NA", "No aplica"),
    CodigoOtro("p13_comb_cocina", "1", "Gas"),
    CodigoOtro("p13_comb_cocina", "2", "Parafina o petróleo"),
    CodigoOtro("p13_comb_cocina", "3", "Leña"),
    CodigoOtro("p13_comb_cocina", "4", "Pellet"),
    CodigoOtro("p13_comb_cocina", "5", "Carbón"),
    CodigoOtro("p13_comb_cocina", "6", "Electricidad"),
    CodigoOtro("p13_comb_cocina", "7",
               "Energía solar (ej. cocina u horno solar)"),
    CodigoOtro("p13_comb_cocina", "8",
               "No utiliza fuente de energía o combustible para cocinar"),
    CodigoOtro("p13_comb_cocina", "-99", "No respuesta"),
    CodigoOtro("p13_comb_cocina", "NA", "No aplica"),
    CodigoOtro("p14_comb_calefaccion", "1", "Gas"),
    CodigoOtro("p14_comb_calefaccion", "2", "Parafina o petróleo"),
    CodigoOtro("p14_comb_calefaccion", "3", "Leña"),
    CodigoOtro("p14_comb_calefaccion", "4", "Pellet"),
    CodigoOtro("p14_comb_calefaccion", "5", "Carbón"),
    CodigoOtro("p14_comb_calefaccion", "6", "Electricidad"),
    CodigoOtro("p14_comb_calefaccion", "7", "Otra"),
    CodigoOtro("p14_comb_calefaccion", "8",
               "No utiliza fuente de energía o combustible para calefaccionar"),
    CodigoOtro("p14_comb_calefaccion", "-99", "No respuesta"),
    CodigoOtro("p14_comb_calefaccion", "NA", "No aplica"),
    CodigoOtro("p15a_serv_tel_movil", "1", "Sí"),
    CodigoOtro("p15a_serv_tel_movil", "2", "No"),
    CodigoOtro("p15a_serv_tel_movil", "-99", "No respuesta"),
    CodigoOtro("p15a_serv_tel_movil", "NA", "No aplica"),
    CodigoOtro("p15b_serv_compu", "1", "Sí"),
    CodigoOtro("p15b_serv_compu", "2", "No"),
    CodigoOtro("p15b_serv_compu", "-99", "No respuesta"),
    CodigoOtro("p15b_serv_compu", "NA", "No aplica"),
    CodigoOtro("p15d_serv_internet_fija", "1", "Sí"),
    CodigoOtro("p15d_serv_internet_fija", "2", "No"),
    CodigoOtro("p15d_serv_internet_fija", "-99", "No respuesta"),
    CodigoOtro("p15d_serv_internet_fija", "NA", "No aplica"),
    CodigoOtro("p15e_serv_internet_movil", "1", "Sí"),
    CodigoOtro("p15e_serv_internet_movil", "2", "No"),
    CodigoOtro("p15e_serv_internet_movil", "-99", "No respuesta"),
    CodigoOtro("p15e_serv_internet_movil", "NA", "No aplica"),
    CodigoOtro("tipologia_hogar", "1", "Unipersonal"),
    CodigoOtro("tipologia_hogar", "2", "Nuclear monoparental"),
    CodigoOtro("tipologia_hogar", "3", "Nuclear pareja sin hijos"),
    CodigoOtro("tipologia_hogar", "4", "Nuclear pareja con hijos"),
    CodigoOtro("tipologia_hogar", "5", "Extenso"),
    CodigoOtro("tipologia_hogar", "6", "Compuesto"),
    CodigoOtro("tipologia_hogar", "7", "Sin núcleo"),
    CodigoOtro("tipologia_hogar", "NA", "No aplica"),
    CodigoOtro("parentesco", "1", "Jefe/a de hogar"),
    CodigoOtro("parentesco", "2", "Esposo/a o cónyuge"),
    CodigoOtro("parentesco", "3", "Conviviente por unión civil"),
    CodigoOtro("parentesco", "4", "Conviviente de hecho o pareja"),
    CodigoOtro("parentesco", "5", "Hijo/a"),
    CodigoOtro("parentesco", "6", "Hijo/a del cónyuge, conviviente o pareja"),
    CodigoOtro("parentesco", "7", "Hermano/a"),
    CodigoOtro("parentesco", "8", "Padre/Madre"),
    CodigoOtro("parentesco", "9", "Cuñado/a"),
    CodigoOtro("parentesco", "10", "Suegro/a"),
    CodigoOtro("parentesco", "11", "Yerno/Nuera"),
    CodigoOtro("parentesco", "12", "Nieto/a"),
    CodigoOtro("parentesco", "13", "Abuelo/a"),
    CodigoOtro("parentesco", "14", "Otro Pariente"),
    CodigoOtro("parentesco", "15", "No Pariente"),
    CodigoOtro("parentesco", "16", "Servicio doméstico puertas adentro"),
    CodigoOtro("parentesco", "17", "Persona en vivienda colectiva"),
    CodigoOtro("parentesco", "19", "Persona en operativo calle"),
    CodigoOtro("sexo", "1", "Hombre"),
    CodigoOtro("sexo", "2", "Mujer"),
    CodigoOtro("edad", "0,0590277777777778", "Válidos"),
    CodigoOtro("edad", "-66", "Valor suprimido por anonimización"),
    CodigoOtro("p23_est_civil", "1", "Casado/a"),
    CodigoOtro("p23_est_civil", "2",
               "Conviviente o pareja sin acuerdo de unión civil"),
    CodigoOtro("p23_est_civil", "3",
               "Conviviente civil (con acuerdo de unión civil)"),
    CodigoOtro("p23_est_civil", "4", "Anulado/a"),
    CodigoOtro("p23_est_civil", "5", "Separado/a"),
    CodigoOtro("p23_est_civil", "6", "Divorciado/a"),
    CodigoOtro("p23_est_civil", "7", "Viudo/a"),
    CodigoOtro("p23_est_civil", "8", "Soltero/a"),
    CodigoOtro("p23_est_civil", "-99", "No respuesta"),
    CodigoOtro("p23_est_civil", "NA", "No aplica"),
    CodigoOtro("p25_lug_nacimiento_rec", "1", "Sí"),
    CodigoOtro("p25_lug_nacimiento_rec", "2", "No"),
    CodigoOtro("p25_lug_nacimiento_rec", "-99", "No respuesta"),
    CodigoOtro("p27_nacionalidad", "1", "Chilena (exclusivamente)"),
    CodigoOtro("p27_nacionalidad", "2",
               "Chilena y otra (doble nacionalidad)"),
    CodigoOtro("p27_nacionalidad", "3", "Otra nacionalidad"),
    CodigoOtro("p27_nacionalidad", "-99", "No respuesta"),
    CodigoOtro("p27_nacionalidad", "-66", "Valor suprimido por anonimización"),
    CodigoOtro("p31_religion", "1", "Católica"),
    CodigoOtro("p31_religion", "2", "Evangélica o Protestante"),
    CodigoOtro("p31_religion", "5",
               "Iglesia de Jesucristo de los Santos de los Últimos Días"),
    CodigoOtro("p31_religion", "10", "Testigo de Jehová"),
    CodigoOtro("p31_religion", "12", "Ninguna"),
    CodigoOtro("p31_religion", "999", "Otra religión o credo"),
    CodigoOtro("p31_religion", "-99", "No respuesta"),
    CodigoOtro("p31_religion", "-66", "Valor suprimido por anonimización"),
    CodigoOtro("p31_religion", "NA", "No aplica"),
    CodigoOtro("p31_religion_rec", "1", "Sí"),
    CodigoOtro("p31_religion_rec", "2", "No"),
    CodigoOtro("p31_religion_rec", "-99", "No respuesta"),
    CodigoOtro("p31_religion_rec", "NA", "No aplica"),
    CodigoOtro("p37_alfabet", "1", "Sí"),
    CodigoOtro("p37_alfabet", "2", "No"),
    CodigoOtro("p37_alfabet", "-99", "No respuesta"),
    CodigoOtro("p37_alfabet", "NA", ""),
    CodigoOtro("depend_econ_deficit_hab", "1", "Económicamente independiente"),
    CodigoOtro("depend_econ_deficit_hab", "2", "Económicamente dependiente"),
    CodigoOtro("depend_econ_deficit_hab", "-99", "No respuesta")
]
